pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/deploy']],
                    extensions: [[$class: 'PathRestriction', excludedRegions: '', includedRegions: 'admin-service/.*']],
                    userRemoteConfigs: [[url: 'https://github.com/playdata-final-project-team/Wesell.git']]
                ])
            }
        }
        stage('Gradle Build') {
            steps {
                dir("admin-service") {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build -x test'
                }
            }
        }
        stage('Build and push Docker image') {
            steps {
                script {
                    dir("admin-service") {
                        // Docker Hub Credentials 설정
                        withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                            // Docker Build 및 Push
                            sh "docker build -t lbs991218/wesell:admin-service ."
                            sh "docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD"
                            sh "docker push lbs991218/wesell:admin-service"
                        }
                    }
                }
            }
        }
        stage('Deploy to EC2') {
            steps {
                script {
                    // EC2에 접속하여 Docker 컨테이너 관리
                    sh """
                            su ubuntu
                            ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-144-42-103.us-east-2.compute.amazonaws.com '
                            sudo docker stop \$(sudo docker ps -q) || true
                            sudo docker rm \$(sudo docker ps -a -q) || true
                            sudo docker rmi \$(sudo docker images -q) || true
                            sudo docker pull lbs991218/wesell:admin-service
                            sudo docker run -d -p 8081:8081 lbs991218/wesell:admin-service
                        '
                    """
                }
            }
        }
    }
}
