pipeline {
    agent any
    environment {
        SERVER_NAME = 'admin-service'
        DOCKER_REGISTRY = 'https://registry.hub.docker.com'
        DOCKER_REPO = 'lbs991218/wesell'
        SSH_USER = 'ubuntu'
        EC2_HOST = 'ec2-3-144-42-103.us-east-2.compute.amazonaws.com'
        DOCKER_IMAGE_TAG = "${DOCKER_REPO}:${SERVER_NAME}"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/deploy']],
                    extensions: [[$class: 'PathRestriction', excludedRegions: '', includedRegions: "${SERVER_NAME}/.*"]],
                    userRemoteConfigs: [[url: 'https://github.com/playdata-final-project-team/Wesell.git']]
                ])
            }
        }
        stage('Gradle Build') {
            steps {
                dir("${SERVER_NAME}") {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build -x test'
                }
            }
        }
        stage('Build and push Docker image') {
            steps {
                script {
                    dir("${SERVER_NAME}") {
                        docker.withRegistry("${DOCKER_REGISTRY}", 'dockerhub-credentials') {
                            def app = docker.build("${DOCKER_IMAGE_TAG}", "-f Dockerfile .")
                            app.push("${SERVER_NAME}")
                        }
                    }
                }
            }
        }
        stage('Deploy to EC2') {
            steps {
                dir("${SERVER_NAME}") {
                    sh """
                        ssh -o StrictHostKeyChecking=no ${SSH_USER}@${EC2_HOST} '
                            sudo docker stop \$(sudo docker ps -q) || true
                            sudo docker rm \$(sudo docker ps -a -q) || true
                            sudo docker rmi \$(sudo docker images -q) || true
                            sudo docker pull ${DOCKER_IMAGE_TAG}
                            sudo docker run -d -p 8081:8081 ${DOCKER_IMAGE_TAG}
                        '
                    """
                }
            }
        }
    }
}