pipeline {
    agent any

    tools {
        nodejs "NodeJS 18.17.1"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/builds']],
                    extensions: [[$class: 'PathRestriction', excludedRegions: '', includedRegions: 'front-end/.*']],
                    userRemoteConfigs: [[url: 'https://github.com/playdata-final-project-team/Wesell.git']]
                ])
            }
        }

        stage('Build and push Docker image') {
            steps {
                script {
                    dir('front-end') {
                        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-credentials') {
                            def app = docker.build("lbs991218/wesell:front-server", "-f Dockerfile .")
                            app.push("latest")
                    }
                }
            }
        }
    }

        stage('Deploy to EC2') {
            steps {
                dir('front-end') {
                    sh """
                        ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-191-195-236.us-east-2.compute.amazonaws.com '
                            sudo docker stop \$(sudo docker ps -q) || true
                            sudo docker rm \$(sudo docker ps -a -q) || true
                            sudo docker rmi \$(sudo docker images -q) || true
                            sudo docker pull lbs991218/wesell:front-server
                            sudo docker run -d -p 3000:3000 lbs991218/wesell:front-server
                        '
                    """
                }
            }
        }
    }
}